haySchool/haySchool/Controllers/DersController.cs
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using haySchool.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace haySchool.Controllers
{
    public class DersController : Controller
    {



        public IActionResult Index()
        {


            Genel genel = new Genel();
            genel.OpenConection();
            NpgsqlDataReader datareader = genel.DataReader("Select * From dersler where ders_aktif=true");
            List<Ders> displayders = new List<Ders>();

            while (datareader.Read())
            {
                var ders = new Ders();
                ders.ders_id = Convert.ToInt32(datareader["ders_id"]);
                ders.ders_adi = datareader["ders_adi"].ToString();
                displayders.Add(ders);
            }
            genel.CloseConnection();
            return View(displayders);
        }



        [HttpGet]
        public IActionResult DersEkle()
        {
            return View();
        }


        [HttpPost]
        public IActionResult DersEkle(Ders ders)
        {
            string constr = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(constr))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("ders_ekle", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("p_ders_adi", ders.ders_adi);
                    ders.ders_id = Convert.ToInt32(command.ExecuteScalar());

                }
                connection.Close();
            }

            //return View(ders);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DersGuncelle(int id)
        {
         
            Ders ders = new Ders();
            DataTable datatable = new DataTable();
            using (NpgsqlConnection connection = new NpgsqlConnection(Genel.conString))
            {
                connection.Open();
                string query = "select* from dersler where ders_id=@ders_id";
                NpgsqlDataAdapter npgsqlDataAdapter = new NpgsqlDataAdapter(query, connection);
                npgsqlDataAdapter.SelectCommand.Parameters.AddWithValue("@ders_id", id);
                npgsqlDataAdapter.Fill(datatable);

            }
            if (datatable.Rows.Count == 1)
            {
                ders.ders_id = Convert.ToInt32(datatable.Rows[0][0].ToString());
                ders.ders_adi = datatable.Rows[0][1].ToString();

                return View(ders);
            }
            else

                return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult DersGuncelle(Ders ders)
        {
            string constr = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(constr))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("ders_guncelle", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    command.Parameters.AddWithValue("p_ders_id", ders.ders_id);
                    command.Parameters.AddWithValue("p_ders_adi", ders.ders_adi);

                    command.ExecuteNonQuery();

                }
                connection.Close();
            }

            return RedirectToAction("Index");
        }

        public ActionResult DersSil(int id)
        {
          
            using (NpgsqlConnection connection = new NpgsqlConnection(Genel.conString))
            {
                connection.Open();

                using (NpgsqlCommand command = new NpgsqlCommand("ders_sil", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("p_ders_id", id);
                    command.ExecuteNonQuery();
                }
                connection.Close();
            }
            return RedirectToAction("Index");
        }


    }




}

haySchool/haySchool/Controllers/EtutController.cs
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using haySchool.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace haySchool.Controllers
{
    public class EtutController : Controller
    {
        public IActionResult Index()
        {
            Genel genel = new Genel();
            genel.OpenConection();
            NpgsqlDataReader datareader = genel.DataReader("Select etut_id, etut_ogrenci_id, etut_ders_id,etut_sinav_id, " +
                " ogrenci_id, ogrenci_adi, ogrenci_soyadi,ders_id,ders_adi" +
                " from etutler" +
                " inner join ogrenciler on etutler.etut_ogrenci_id=ogrenciler.ogrenci_id " +
                " inner join sinavlar on etutler.etut_sinav_id=sinavlar.sinav_id " +
                "inner join dersler on etutler.etut_ders_id=dersler.ders_id where etut_aktif=true");
            List<Etut> displayetut = new List<Etut>();
            while (datareader.Read())
            {


                var etut = new Etut();
                etut.etut_id = Convert.ToInt32(datareader["etut_id"]);
                etut.etut_ogrenci_adi = datareader["ogrenci_adi"] + " " + datareader["ogrenci_soyadi"].ToString();
                etut.etut_ders_adi = datareader["ders_adi"].ToString();
                etut.etut_sinav_id = Convert.ToInt32(datareader["etut_sinav_id"]);


                displayetut.Add(etut);
            }
            genel.CloseConnection();
            return View(displayetut);


        }
        [HttpGet]
        public IActionResult EtutEkle()
        {

            List<SelectListItem> values1 = new List<SelectListItem>();
            List<SelectListItem> values2 = new List<SelectListItem>();
            List<SelectListItem> values3 = new List<SelectListItem>();

            string connectionString = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("SELECT * FROM ogrenciler", connection))
                {
                    using (NpgsqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            values1.Add(new SelectListItem
                            {
                                Text = reader["ogrenci_adi"].ToString() + " " + reader["ogrenci_soyadi"].ToString(),
                                Value = reader["ogrenci_id"].ToString()
                            });
                        }
                    }
                    ViewBag.v8 = values1;


                }



            }
            //using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            //{
            //    connection.Open();
            //    using (NpgsqlCommand command = new NpgsqlCommand("SELECT * FROM dersler", connection))
            //    {
            //        using (NpgsqlDataReader reader = command.ExecuteReader())
            //        {
            //            while (reader.Read())
            //            {
            //                values2.Add(new SelectListItem
            //                {
            //                    Text = reader["ders_adi"].ToString(),

            //                    Value = reader["ders_id"].ToString()


            //            });
            //            }
            //        }

            //        ViewBag.v9 = values2;

            //    }

            //}
            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("SELECT sinav_ders_id, sinav_date, sinav_id, ders_adi, ders_id" +
                    " FROM sinavlar inner join dersler on sinavlar.sinav_ders_id=dersler.ders_id", connection))
                {
                    using (NpgsqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            values3.Add(new SelectListItem
                            {
                                Text = reader["ders_adi"].ToString() + " " + reader["sinav_date"].ToString(),
                                Value = reader["sinav_id"].ToString()
                            });
                            values2.Add(new SelectListItem
                            {
                                Text = reader["ders_adi"].ToString(),
                                Value = reader["sinav_ders_id"].ToString()
                            });
                        }
                    }
                    ViewBag.v9 = values2;
                    ViewBag.v10 = values3;

                }

            }

            return View();
        }


        [HttpPost]
        public IActionResult EtutEkle(Etut etut)
        {

            string constr = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(constr))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("etut_ekle", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("p_etut_ogrenci_id", etut.etut_ogrenci_id);
                    command.Parameters.AddWithValue("p_etut_ders_id", etut.etut_ders_id);
                    command.Parameters.AddWithValue("p_etut_sinav_id", etut.etut_sinav_id);
                    etut.etut_id = Convert.ToInt32(command.ExecuteScalar());

                }
                connection.Close();
            }


            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult EtutGuncelle(int id)
        {


            List<SelectListItem> values10 = new List<SelectListItem>();
            List<SelectListItem> values11 = new List<SelectListItem>();
            List<SelectListItem> values12 = new List<SelectListItem>();


            string connectionString = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("SELECT sinav_ders_id, sinav_date, sinav_id, ders_adi, ders_id" +
                    " FROM sinavlar inner join dersler on sinavlar.sinav_ders_id=dersler.ders_id", connection))
                {
                    using (NpgsqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            values10.Add(new SelectListItem
                            {
                                Text = reader["ders_adi"].ToString() + " " + reader["sinav_date"].ToString(),
                                Value = reader["sinav_id"].ToString()
                            });
                            values11.Add(new SelectListItem
                            {
                                Text = reader["ders_adi"].ToString(),
                                Value = reader["sinav_ders_id"].ToString()
                            });
                        }
                    }
                    ViewBag.v10 = values10;
                    ViewBag.v11 = values11;

                }

            }


            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("SELECT * FROM ogrenciler", connection))
                {
                    using (NpgsqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            values12.Add(new SelectListItem
                            {
                                Text = reader["ogrenci_adi"].ToString() + " " + reader["ogrenci_soyadi"].ToString(),
                                Value = reader["ogrenci_id"].ToString()
                            });
                        }
                    }
                    ViewBag.v12 = values12;


                }



            }
            Etut etut = new Etut();
            DataTable datatable = new DataTable();

            using (NpgsqlConnection connection = new NpgsqlConnection(Genel.conString))
            {
                connection.Open();
                string query = "select* from etutler where etut_id=@etut_id";
                NpgsqlDataAdapter npgsqlDataAdapter = new NpgsqlDataAdapter(query, connection);
                npgsqlDataAdapter.SelectCommand.Parameters.AddWithValue("@etut_id", id);
                npgsqlDataAdapter.Fill(datatable);

            }
            if (datatable.Rows.Count == 1)
            {
                etut.etut_id = Convert.ToInt32(datatable.Rows[0][0].ToString());
                etut.etut_ogrenci_id = Convert.ToInt32(datatable.Rows[0][1].ToString());
                etut.etut_ders_id = Convert.ToInt32(datatable.Rows[0][2].ToString());

                etut.etut_sinav_id = Convert.ToInt32(datatable.Rows[0][3].ToString());

                return View(etut);
            }
            else

                return RedirectToAction("Index");

        }


        [HttpPost]
        public IActionResult EtutGuncelle(Etut etut)
        {
            string constr = Genel.conString;

            using (NpgsqlConnection connection = new NpgsqlConnection(constr))
            {
                connection.Open();
                using (NpgsqlCommand command = new NpgsqlCommand("etut_guncelle", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

haySchool/haySchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - haySchool</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: whitesmoke;">
	<p></p>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,117,121,1) 39%, rgba(4,119,193,1) 72%, rgba(3,139,206,1) 78%, rgba(2,156,217,1) 83%, rgba(2,166,224,1) 86%, rgba(93,192,212,1) 100%);  ">
			<div class="container">
				
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" style="background-color:#aec9cf;"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1" style="padding-top:5px; font-size:larger;">
						<li class="nav-item">
							<a class="nav-link text-light"style="color:white; height:55px; font-family:'Lucida Handwriting'; padding-top:8px; font-size:x-large;" asp-area="" asp-controller="Home" asp-action="Index">haySchool</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Sinif" asp-action="Index">Sınıflar</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Ders" asp-action="Index">Dersler</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Ogrenci" asp-action="Index">Öğrenciler</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Veli" asp-action="Index">Veliler</a>
						</li>
						@*<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Taksit" asp-action="Index">Taksitler</a>
						</li>*@
					
						@*------------------------*@
						@*<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="color:white;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  Sınıflar
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						  <a class="dropdown-item" asp-controller="Sinif" asp-action="Index">101</a>
						 
						  <a class="dropdown-item" href="#">Another action</a>
						  <div class="dropdown-divider"></div>
						  <a class="dropdown-item" href="#">Something else here</a>
						</div>
					  </li>*@
					  @*---------------------------------*@

					@*	<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Ogretmen" asp-action="Index">Öğretmenler</a>
						</li>*@
						@*<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Sinav" asp-action="Index">Sınavlar</a>
						</li>*@
						@*<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Etut" asp-action="Index">Etütler</a>
						</li>*@

					@*	<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Odeme" asp-action="Index">Ödemeler</a>
						</li>*@

						<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="color:white;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  Ödeme İşlemleri
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						 
						 
						  <a class="dropdown-item" href="/Odeme/Index">Ödemeler</a>
						  <a class="dropdown-item" href="/OdemeTur/Index">Ödeme Türleri</a>
						
						</div>
					  </li>


					  	<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="color:white;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  Sınav/Sonuç/Etüt
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						 
						 
						  <a class="dropdown-item" href="/Sinav/Index">Sınav İşlemleri</a>
						  <a class="dropdown-item" href="/Sonuc/Index">Sonuç İşlemleri</a>
						  <a class="dropdown-item" href="/Etut/Index">Etüt İşlemleri</a>
						
						</div>
					  </li>
						

					
						<div class="collapse navbar-collapse justify-content-end ">
							<ul class="nav navbar-nav ">

								<li class="nav-item dropdown">
									<a class="nav-link " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

										<img src="~/farmerwom.png" style="weight:40px; height:40px" />
									</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
										<a class="dropdown-item" href="#">Action</a>
										<a class="dropdown-item" href="#">Another action</a>
										<a class="dropdown-item" href="#">Something else here</a>
									</div>

								</li>



							</ul>
						</div>


					</ul>

				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
            &copy; 2022 haySchool - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color:saddlebrown;">EcrenEsen&BerfinDalar</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

haySchool/haySchool/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SurveyAppCalik</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:#2c3949">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts",false)
    <div>
        @RenderBody()
    </div>
</body>
</html>